{{- if .Values.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leanix-k8s-connector
  labels:
{{ include "leanix-k8s-connector.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources:
  # - bindings
  # - configmaps
  # - endpoints
  # - events
  # - limitranges
  - namespaces
  - nodes
  # - persistentvolumeclaims
  - pods
  - replicationcontrollers
  # - resourcequotas
  # - serviceaccounts
  # - services
  verbs:
  - get
  - list
  - watch
# - apiGroups: ["apiextensions.k8s.io"]
#   resources:
#   - customresourcedefinitions
#   verbs:
#   - get
#   - list
#   - watch
- apiGroups: ["apps"]
  resources:
  # - controllerrevisions
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
# - apiGroups: ["autoscaling"]
#   resources:
#   - horizontalpodautoscalers
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups: ["batch"]
#   resources:
#   - cronjobs
#   - jobs
#   verbs:
#   - get
#   - list
#   - watch
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  # - ingresses
  # - networkpolicies
  # - podsecuritypolicies
  - replicasets
  verbs:
  - get
  - list
  - watch
# - apiGroups: ["metrics.k8s.io"]
#   resources:
#   - nodes
#   - pods
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups: ["networking.k8s.io"]
#   resources:
#   - networkpolicies
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups: ["policy"]
#   resources:
#   - poddisruptionbudgets
#   - podsecuritypolicies
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups: ["rbac.authorization.k8s.io"]
#   resources:
#   - clusterrolebindings
#   - clusterroles
#   - rolebindings
#   - roles
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups: ["scheduling.k8s.io"]
#   resources:
#   - priorityclasses
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups: ["storage.k8s.io"]
#   resources:
#   - storageclasses
#   - volumeattachments
#   verbs:
#   - get
#   - list
#   - watch
{{- end -}}