{{- if and (.Values.rbac) (not .Values.clusterRoleAlreadyCreated) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leanix-k8s-connector-{{ .Release.Name }}
  labels:
{{ include "leanix-k8s-connector.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes","persistentvolume","persistentvolumeclaim","namespaces","services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments","daemonsets","statefulsets","replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs","jobs"]
  verbs: ["get", "list", "watch"]
{{- end -}}
