{{- if .Values.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leanix-k8s-connector
  labels:
{{ include "leanix-k8s-connector.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - pods
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
{{- end -}}