{{- if and (.Values.rbac) ( .Values.createClusterRoleBinding) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leanix-k8s-connector-{{ .Release.Name }}
  labels:
{{ include "leanix-k8s-connector.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leanix-k8s-connector-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: leanix-k8s-connector-{{ .Release.Name }}
  namespace: test1
{{- end -}}
