{{- if and (.Values.rbac) (not .Values.clusterRoleAlreadyCreated) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leanix-k8s-connector-{{ .Release.Name }}
  labels:
{{ include "leanix-k8s-connector.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leanix-k8s-connector
subjects:
- kind: ServiceAccount
  name: leanix-k8s-connector
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leanix-k8s-connector-view-{{ .Release.Name }}
  labels:
{{ include "leanix-k8s-connector.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: leanix-k8s-connector-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}