apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "leanix-k8s-connector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "leanix-k8s-connector.labels" . | indent 4 }}
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.rbac }}
          serviceAccountName: leanix-k8s-connector
          {{- end }}
          containers:
          - name: connector
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            args:
            - "--clustername"
            - "{{ .Values.args.clustername }}"
            {{- if .Values.args.verbose }}
            - "--verbose"
            {{- end }}
            - "--storage-backend"
            - "{{ .Values.args.storageBackend }}"
            {{- if eq .Values.args.storageBackend "file" }}
            - "--local-file-path"
            - "{{ .Values.args.localFilePath }}"
            {{- else if eq .Values.args.storageBackend "azureblob" }}
            - "--azure-account-key"
            - "{{ .Values.args.azureblob.accountKey }}"
            - "--azure-account-name"
            - "{{ .Values.args.azureblob.accountName }}"
            - "--azure-container"
            - "{{ .Values.args.azureblob.container }}"
            {{- end }}
            - "--log-file"
            - "{{ .Values.args.logFile }}"
            - "--connector-id"
            - "{{ .Values.args.connectorID }}"
            resources:
              requests:
                cpu: {{ .Values.resources.requests.cpu }}
                memory: {{ .Values.resources.requests.memory }}
              limits:
                cpu: {{ .Values.resources.limits.cpu }}
                memory: {{ .Values.resources.limits.memory }}
          restartPolicy: OnFailure
