# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  displayName: Prepare Go environment
  inputs:
    version: '1.12'
- task: Go@0
  displayName: Download deps
  inputs:
    command: 'get'
- task: Go@0
  displayName: Test
  inputs:
    command: 'test'
    arguments: './pkg/...'
- task: Go@0
  displayName: Build
  inputs:
    command: 'build'
    arguments: '-o bin/leanix-k8s-connector -ldflags "-X github.com/leanix/leanix-k8s-connector/pkg/version.VERSION=$(Build.SourceVersion) -extldflags -static" ./cmd/leanix-k8s-connector/main.go'
