# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PrepareBuildEnv
  jobs:
  - job: GoVersion
    steps:
    - task: GoTool@0
      inputs:
        version: '1.12'
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - task: Go@0
      inputs:
        command: 'test'
        arguments: './pkg/...'
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Go@0
      inputs:
        command: 'test'
        arguments: './pkg/...'
