# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.12'
- task: Go@0
  inputs:
    command: 'test'
    arguments: './pkg/...'
- task: Go@0
  inputs:
    command: 'test'
    arguments: './pkg/...'
