// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	models "github.com/leanix/leanix-k8s-connector/pkg/iris/common/models"
	workloadsmodels "github.com/leanix/leanix-k8s-connector/pkg/iris/workloads/models"
	mock "github.com/stretchr/testify/mock"
)

// EcstWorkloadEventBuilder is an autogenerated mock type for the EcstWorkloadEventBuilder type
type EcstWorkloadEventBuilder struct {
	mock.Mock
}

type EcstWorkloadEventBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *EcstWorkloadEventBuilder) EXPECT() *EcstWorkloadEventBuilder_Expecter {
	return &EcstWorkloadEventBuilder_Expecter{mock: &_m.Mock}
}

// Body provides a mock function with given fields: body
func (_m *EcstWorkloadEventBuilder) Body(body models.DiscoveryBody) workloadsmodels.EcstEventBuilder {
	ret := _m.Called(body)

	var r0 workloadsmodels.EcstEventBuilder
	if rf, ok := ret.Get(0).(func(models.DiscoveryBody) workloadsmodels.EcstEventBuilder); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(workloadsmodels.EcstEventBuilder)
		}
	}

	return r0
}

// EcstWorkloadEventBuilder_Body_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Body'
type EcstWorkloadEventBuilder_Body_Call struct {
	*mock.Call
}

// Body is a helper method to define mock.On call
//   - body models.DiscoveryBody
func (_e *EcstWorkloadEventBuilder_Expecter) Body(body interface{}) *EcstWorkloadEventBuilder_Body_Call {
	return &EcstWorkloadEventBuilder_Body_Call{Call: _e.mock.On("Body", body)}
}

func (_c *EcstWorkloadEventBuilder_Body_Call) Run(run func(body models.DiscoveryBody)) *EcstWorkloadEventBuilder_Body_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.DiscoveryBody))
	})
	return _c
}

func (_c *EcstWorkloadEventBuilder_Body_Call) Return(_a0 workloadsmodels.EcstEventBuilder) *EcstWorkloadEventBuilder_Body_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EcstWorkloadEventBuilder_Body_Call) RunAndReturn(run func(models.DiscoveryBody) workloadsmodels.EcstEventBuilder) *EcstWorkloadEventBuilder_Body_Call {
	_c.Call.Return(run)
	return _c
}

// Build provides a mock function with given fields:
func (_m *EcstWorkloadEventBuilder) Build() models.DiscoveryEvent {
	ret := _m.Called()

	var r0 models.DiscoveryEvent
	if rf, ok := ret.Get(0).(func() models.DiscoveryEvent); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.DiscoveryEvent)
	}

	return r0
}

// EcstWorkloadEventBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type EcstWorkloadEventBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *EcstWorkloadEventBuilder_Expecter) Build() *EcstWorkloadEventBuilder_Build_Call {
	return &EcstWorkloadEventBuilder_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *EcstWorkloadEventBuilder_Build_Call) Run(run func()) *EcstWorkloadEventBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EcstWorkloadEventBuilder_Build_Call) Return(_a0 models.DiscoveryEvent) *EcstWorkloadEventBuilder_Build_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EcstWorkloadEventBuilder_Build_Call) RunAndReturn(run func() models.DiscoveryEvent) *EcstWorkloadEventBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with given fields: header
func (_m *EcstWorkloadEventBuilder) Header(header models.HeaderProperties) workloadsmodels.EcstEventBuilder {
	ret := _m.Called(header)

	var r0 workloadsmodels.EcstEventBuilder
	if rf, ok := ret.Get(0).(func(models.HeaderProperties) workloadsmodels.EcstEventBuilder); ok {
		r0 = rf(header)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(workloadsmodels.EcstEventBuilder)
		}
	}

	return r0
}

// EcstWorkloadEventBuilder_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type EcstWorkloadEventBuilder_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
//   - header models.HeaderProperties
func (_e *EcstWorkloadEventBuilder_Expecter) Header(header interface{}) *EcstWorkloadEventBuilder_Header_Call {
	return &EcstWorkloadEventBuilder_Header_Call{Call: _e.mock.On("Header", header)}
}

func (_c *EcstWorkloadEventBuilder_Header_Call) Run(run func(header models.HeaderProperties)) *EcstWorkloadEventBuilder_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.HeaderProperties))
	})
	return _c
}

func (_c *EcstWorkloadEventBuilder_Header_Call) Return(_a0 workloadsmodels.EcstEventBuilder) *EcstWorkloadEventBuilder_Header_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EcstWorkloadEventBuilder_Header_Call) RunAndReturn(run func(models.HeaderProperties) workloadsmodels.EcstEventBuilder) *EcstWorkloadEventBuilder_Header_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewEcstWorkloadEventBuilder interface {
	mock.TestingT
	Cleanup(func())
}

// NewEcstWorkloadEventBuilder creates a new instance of EcstWorkloadEventBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEcstWorkloadEventBuilder(t mockConstructorTestingTNewEcstWorkloadEventBuilder) *EcstWorkloadEventBuilder {
	mock := &EcstWorkloadEventBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
