// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	models "github.com/leanix/leanix-k8s-connector/pkg/iris/common/models"
	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

type API_Expecter struct {
	mock *mock.Mock
}

func (_m *API) EXPECT() *API_Expecter {
	return &API_Expecter{mock: &_m.Mock}
}

// GetConfiguration provides a mock function with given fields: configurationName
func (_m *API) GetConfiguration(configurationName string) ([]byte, error) {
	ret := _m.Called(configurationName)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(configurationName)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(configurationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(configurationName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// API_GetConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfiguration'
type API_GetConfiguration_Call struct {
	*mock.Call
}

// GetConfiguration is a helper method to define mock.On call
//   - configurationName string
func (_e *API_Expecter) GetConfiguration(configurationName interface{}) *API_GetConfiguration_Call {
	return &API_GetConfiguration_Call{Call: _e.mock.On("GetConfiguration", configurationName)}
}

func (_c *API_GetConfiguration_Call) Run(run func(configurationName string)) *API_GetConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *API_GetConfiguration_Call) Return(_a0 []byte, _a1 error) *API_GetConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *API_GetConfiguration_Call) RunAndReturn(run func(string) ([]byte, error)) *API_GetConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetScanResults provides a mock function with given fields: configurationId
func (_m *API) GetScanResults(configurationId string) ([]models.DiscoveryEvent, error) {
	ret := _m.Called(configurationId)

	var r0 []models.DiscoveryEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.DiscoveryEvent, error)); ok {
		return rf(configurationId)
	}
	if rf, ok := ret.Get(0).(func(string) []models.DiscoveryEvent); ok {
		r0 = rf(configurationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DiscoveryEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(configurationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// API_GetScanResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScanResults'
type API_GetScanResults_Call struct {
	*mock.Call
}

// GetScanResults is a helper method to define mock.On call
//   - configurationId string
func (_e *API_Expecter) GetScanResults(configurationId interface{}) *API_GetScanResults_Call {
	return &API_GetScanResults_Call{Call: _e.mock.On("GetScanResults", configurationId)}
}

func (_c *API_GetScanResults_Call) Run(run func(configurationId string)) *API_GetScanResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *API_GetScanResults_Call) Return(_a0 []models.DiscoveryEvent, _a1 error) *API_GetScanResults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *API_GetScanResults_Call) RunAndReturn(run func(string) ([]models.DiscoveryEvent, error)) *API_GetScanResults_Call {
	_c.Call.Return(run)
	return _c
}

// PostEcstResults provides a mock function with given fields: ecstResults
func (_m *API) PostEcstResults(ecstResults []byte) error {
	ret := _m.Called(ecstResults)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(ecstResults)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// API_PostEcstResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostEcstResults'
type API_PostEcstResults_Call struct {
	*mock.Call
}

// PostEcstResults is a helper method to define mock.On call
//   - ecstResults []byte
func (_e *API_Expecter) PostEcstResults(ecstResults interface{}) *API_PostEcstResults_Call {
	return &API_PostEcstResults_Call{Call: _e.mock.On("PostEcstResults", ecstResults)}
}

func (_c *API_PostEcstResults_Call) Run(run func(ecstResults []byte)) *API_PostEcstResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *API_PostEcstResults_Call) Return(_a0 error) *API_PostEcstResults_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *API_PostEcstResults_Call) RunAndReturn(run func([]byte) error) *API_PostEcstResults_Call {
	_c.Call.Return(run)
	return _c
}

// PostStatus provides a mock function with given fields: status
func (_m *API) PostStatus(status []byte) error {
	ret := _m.Called(status)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// API_PostStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostStatus'
type API_PostStatus_Call struct {
	*mock.Call
}

// PostStatus is a helper method to define mock.On call
//   - status []byte
func (_e *API_Expecter) PostStatus(status interface{}) *API_PostStatus_Call {
	return &API_PostStatus_Call{Call: _e.mock.On("PostStatus", status)}
}

func (_c *API_PostStatus_Call) Run(run func(status []byte)) *API_PostStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *API_PostStatus_Call) Return(_a0 error) *API_PostStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *API_PostStatus_Call) RunAndReturn(run func([]byte) error) *API_PostStatus_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAPI(t mockConstructorTestingTNewAPI) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
