# Default values for leanix-k8s-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac: true

integrationApi:
  enabled: false
  fqdn: ""
  secretName: ""

schedule:
  standard: "*/1 * * * *"
  integrationApi: "0 */1 * * *"

image:
  repository: docker.io/leanix/leanix-k8s-connector
  tag: 2.0.0-beta7
  pullPolicy: Always

args:
  clustername: kubernetes
  connectorID: ""
  connectorVersion: "1.0.0"
  processingMode: partial
  lxWorkspace: ""
  verbose: false
  storageBackend: file
  file:
    localFilePath: "/mnt/leanix-k8s-connector"
    claimName: ""
  azureblob:
    secretName: ""
    container: ""
  blacklistNamespaces:
  - "kube-system"

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
