# Default values for leanix-k8s-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: leanix.azurecr.io/leanix-k8s-connector
  tag: latest
  pullPolicy: Always

args:
  clustername: kubernetes
  verbose: false
  storageBackend: file
  localFilePath: "."
  azureblob:
    accountKey: ""
    accountName: ""
    container: ""
  logFile: ./leanix-k8s-connector.log

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
