# Default values for leanix-k8s-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac: true
clusterRoleAlreadyCreated: false

integrationApi:
  fqdn: ""
  secretName: ""
  datasourceName: ""

schedule:
  standard: "0 */1 * * *"

image:
  repository: leanixacrpublic.azurecr.io/leanix-k8s-connector
  tag: 6.9.2
  pullPolicy: Always

securityContext:
  userId: 65534
  groupId: 65534

args:
  clustername: kubernetes
  connectorID: ""
  connectorVersion: "1.0.0"
  processingMode: full
  lxWorkspace: ""
  verbose: false
  enableCustomStorage: false
  storageBackend: none
  file:
    localFilePath: "/mnt/leanix-k8s-connector"
    claimName: ""
  azureblob:
    secretName: ""
    container: ""
  blacklistNamespaces:
    - "kube-system"
  additionalEnv: {}

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
