apiVersion: v1
entries:
  leanix-k8s-connector:
  - apiVersion: v1
    appVersion: 6.10.8
    created: "2023-02-06T09:18:08.218534172Z"
    description: Retrieves information from Kubernetes cluster
    digest: 0ef64ed22efb17437db39159c47ac8fe75325c96511e74a5b5ab77f8e7261949
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.10.8.tgz
    version: 6.10.8
  - apiVersion: v1
    appVersion: 6.10.7
    created: "2023-02-06T09:18:08.218129568Z"
    description: Retrieves information from Kubernetes cluster
    digest: f98103276c788d36188c39ca2e7c652420082561fb348cfa630488fb2fade19b
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.10.7.tgz
    version: 6.10.7
  - apiVersion: v1
    appVersion: 6.10.5
    created: "2023-02-06T09:18:08.217740564Z"
    description: Retrieves information from Kubernetes cluster
    digest: bafebcce3a277506e1f4dff0087cce829a119e21ccdc2d37350cf1ab9382eb84
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.10.5.tgz
    version: 6.10.5
  - apiVersion: v1
    appVersion: 6.10.4
    created: "2023-02-06T09:18:08.21735486Z"
    description: Retrieves information from Kubernetes cluster
    digest: 9a501b822799c25ce50387eb4be9618c525acbf0d439681cc64771e2ff6ffb73
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.10.4.tgz
    version: 6.10.4
  - apiVersion: v1
    appVersion: 6.10.3
    created: "2023-02-06T09:18:08.216932856Z"
    description: Retrieves information from Kubernetes cluster
    digest: 86cf99c1af06ba0b7b98a2031d7be855ffb579fe031079d5cb2a146caadf9eaf
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.10.3.tgz
    version: 6.10.3
  - apiVersion: v1
    appVersion: 6.10.2
    created: "2023-02-06T09:18:08.216554552Z"
    description: Retrieves information from Kubernetes cluster
    digest: c96a2f4e038c34e355253abec696bec6d5fd7a9d36ba1bf6dd6781467a9a5259
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.10.2.tgz
    version: 6.10.2
  - apiVersion: v1
    appVersion: 6.10.1
    created: "2023-02-06T09:18:08.216162448Z"
    description: Retrieves information from Kubernetes cluster
    digest: 082ce3ee58392ba808ded039f7132c3ac44425f40769722384175cc5fcc87e66
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.10.1.tgz
    version: 6.10.1
  - apiVersion: v1
    appVersion: 6.10.0
    created: "2023-02-06T09:18:08.215544141Z"
    description: Retrieves information from Kubernetes cluster
    digest: 4c407e85756a4b6e9ed5279121bc9b7d9fd85044b5bf9317e1c2d93e866ad864
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.10.0.tgz
    version: 6.10.0
  - apiVersion: v1
    appVersion: 6.9.2
    created: "2023-02-06T09:18:08.226690957Z"
    description: Retrieves information from Kubernetes cluster
    digest: 6bd55a6908aa2889a8b1162688ad5f2734d12bf985bca8795fab85d9e7bd12bc
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.9.2.tgz
    version: 6.9.2
  - apiVersion: v1
    appVersion: 6.9.1
    created: "2023-02-06T09:18:08.226293653Z"
    description: Retrieves information from Kubernetes cluster
    digest: 5f2dc68eee39a9046859b0c8920dc988bee29d273d03f0734efa17adeea7e2bb
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.9.1.tgz
    version: 6.9.1
  - apiVersion: v1
    appVersion: 6.8.4
    created: "2023-02-06T09:18:08.225914849Z"
    description: Retrieves information from Kubernetes cluster
    digest: 1c31c8f77d9340ff4a7cce40578b34e04c81b6b3929636855658214f87e81a82
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.8.4.tgz
    version: 6.8.4
  - apiVersion: v1
    appVersion: 6.8.3
    created: "2023-02-06T09:18:08.225543345Z"
    description: Retrieves information from Kubernetes cluster
    digest: 3544cce736b524ab9089cd12dcca48c31a67dabf4665479c388cbeb7bd98e67c
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.8.3.tgz
    version: 6.8.3
  - apiVersion: v1
    appVersion: 6.8.2
    created: "2023-02-06T09:18:08.225143541Z"
    description: Retrieves information from Kubernetes cluster
    digest: 9b5c09725ca10ad2f27022074fc96be389c8d6c659c50bd55bd9f8b3112d5398
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.8.2.tgz
    version: 6.8.2
  - apiVersion: v1
    appVersion: 6.8.1
    created: "2023-02-06T09:18:08.224476134Z"
    description: Retrieves information from Kubernetes cluster
    digest: 3a259f93e45e96fc61adb04732d3f4add7386f8a30c267fe60ce1b0c0bb76ecc
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.8.1.tgz
    version: 6.8.1
  - apiVersion: v1
    appVersion: 6.8.0
    created: "2023-02-06T09:18:08.223956828Z"
    description: Retrieves information from Kubernetes cluster
    digest: 0e4abbf3773d265f81350f251f8d96fc9af1d14c7cae4bd27df901cd835fbd47
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.8.0.tgz
    version: 6.8.0
  - apiVersion: v1
    appVersion: 6.6.0
    created: "2023-02-06T09:18:08.223199021Z"
    description: Retrieves information from Kubernetes cluster
    digest: 821ac9221077ef8e163ccfd08410c84ed4e479135e4bc73bce99a0d19352799d
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.6.0.tgz
    version: 6.6.0
  - apiVersion: v1
    appVersion: 6.5.2
    created: "2023-02-06T09:18:08.222824417Z"
    description: Retrieves information from Kubernetes cluster
    digest: 66bb48db79d6f711b0a1077be406f769a09ef1063c01aa29303f2b76149715b0
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.5.2.tgz
    version: 6.5.2
  - apiVersion: v1
    appVersion: 6.5.1
    created: "2023-02-06T09:18:08.222448213Z"
    description: Retrieves information from Kubernetes cluster
    digest: 4c254a23a62fc763e00ad3c5368b906de413d8d228e101b3a15481a4d431beef
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.5.1.tgz
    version: 6.5.1
  - apiVersion: v1
    appVersion: 6.5.0
    created: "2023-02-06T09:18:08.221522903Z"
    description: Retrieves information from Kubernetes cluster
    digest: 1da811cd63611a42d99aaee69cbc3982b7ec832f9e30c460dc3e4e504a891ea8
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.5.0.tgz
    version: 6.5.0
  - apiVersion: v1
    appVersion: 6.4.1
    created: "2023-02-06T09:18:08.2211576Z"
    description: Retrieves information from Kubernetes cluster
    digest: 9474bd220dca85ff38d86e2f5ae49b5c76c1c5d2343fa2d6a2a44599f2c5b684
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.4.1.tgz
    version: 6.4.1
  - apiVersion: v1
    appVersion: 6.4.0
    created: "2023-02-06T09:18:08.220777796Z"
    description: Retrieves information from Kubernetes cluster
    digest: bbc9ecd61b72ffd7ae8897074a4cb325541d1d8dec567d56406ff4c172d0d8db
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.4.0.tgz
    version: 6.4.0
  - apiVersion: v1
    appVersion: 6.3.3
    created: "2023-02-06T09:18:08.220417492Z"
    description: Retrieves information from Kubernetes cluster
    digest: f0785c889298cac1eb58ae9380e62457c2b1b73fbfbdccb35f2d85410b50293c
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.3.3.tgz
    version: 6.3.3
  - apiVersion: v1
    appVersion: 6.3.2
    created: "2023-02-06T09:18:08.220057288Z"
    description: Retrieves information from Kubernetes cluster
    digest: 918ec561f0ab03c5039144e7d151e447dac40ad1bace19435ae4be0c21ab6ad2
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.3.2.tgz
    version: 6.3.2
  - apiVersion: v1
    appVersion: 6.3.1
    created: "2023-02-06T09:18:08.219663984Z"
    description: Retrieves information from Kubernetes cluster
    digest: e4ff6114e41c6f7694be5ab006f64ae6620758774610fcbb41357feb71da547c
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.3.1.tgz
    version: 6.3.1
  - apiVersion: v1
    appVersion: 6.3.0
    created: "2023-02-06T09:18:08.21929608Z"
    description: Retrieves information from Kubernetes cluster
    digest: 44973672d6054cd0660a94e71b23bf9cf472f27bc532133981af6f6055e87424
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.3.0.tgz
    version: 6.3.0
  - apiVersion: v1
    appVersion: 6.2.0
    created: "2023-02-06T09:18:08.218931476Z"
    description: Retrieves information from Kubernetes cluster
    digest: 5774478e89bc749ba21ec7f2477bb348788f2bbf6e8b76956eee5c4739de9e46
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.2.0.tgz
    version: 6.2.0
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2023-02-06T09:18:08.215027036Z"
    description: Retrieves information from Kubernetes cluster
    digest: eabf3e49a9d4a0722228cb24872e6dfcc7b9db6b764bc714a74c0941f0d3ea4f
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.1.0.tgz
    version: 6.1.0
  - apiVersion: v1
    appVersion: 6.0.3
    created: "2023-02-06T09:18:08.21447143Z"
    description: Retrieves information from Kubernetes cluster
    digest: 5f1be6a80fc173d45ca60f5da8937abc0fcb2cc14652d6149d9ff2e405568a71
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.0.3.tgz
    version: 6.0.3
  - apiVersion: v1
    appVersion: 6.0.2
    created: "2023-02-06T09:18:08.213708822Z"
    description: Retrieves information from Kubernetes cluster
    digest: ccd112d1de601bfa796c4413ddc2b394f93ec4b66604338a736593168523b327
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.0.2.tgz
    version: 6.0.2
  - apiVersion: v1
    appVersion: 6.0.1
    created: "2023-02-06T09:18:08.213358919Z"
    description: Retrieves information from Kubernetes cluster
    digest: f3b959e24bdbf55314fa6d0a05681ec41dd34b1493b026a3450bf147e62a4b1b
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.0.1.tgz
    version: 6.0.1
  - apiVersion: v1
    appVersion: 6.0.0
    created: "2023-02-06T09:18:08.213005315Z"
    description: Retrieves information from Kubernetes cluster
    digest: c51f68b592c6f608a2f982e8c322280b8fc3aa4ac6ed0d823b2baf24b0877e6b
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.0.0.tgz
    version: 6.0.0
  - apiVersion: v1
    appVersion: 6.0.0-latest
    created: "2023-02-06T09:18:08.212619611Z"
    description: Retrieves information from Kubernetes cluster
    digest: 6545e2a0448f7cb0b546945516fd7cc2c5ab209646ab1cd7b67ab3dd972dd551
    kubeVersion: '>= 1.19.0-0'
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-6.0.0-latest.tgz
    version: 6.0.0-latest
  - apiVersion: v1
    appVersion: 5.0.0
    created: "2023-02-06T09:18:08.212215907Z"
    description: Retrieves information from Kubernetes cluster
    digest: 549a753cf9875ca4eeaf5ecb5c64e76149b30bb8e82eee821f6c81cca27c37cf
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-5.0.0.tgz
    version: 5.0.0
  - apiVersion: v1
    appVersion: 4.0.0
    created: "2023-02-06T09:18:08.211355098Z"
    description: Retrieves information from Kubernetes cluster
    digest: adf5c8ef024857c4a0845a5c659f27bd7f21cdf568fff3445a192425c44fc9a8
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-4.0.0.tgz
    version: 4.0.0
  - apiVersion: v1
    appVersion: 3.0.0
    created: "2023-02-06T09:18:08.210959394Z"
    description: Retrieves information from Kubernetes cluster
    digest: 2927aebc215a1c5175e986135e36a10101e90fa69e7ab22a183049d086f7eddb
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2023-02-06T09:18:08.21053409Z"
    description: Retrieves information from Kubernetes cluster
    digest: 3481723d2374757038495117518c47f634054408ccbd55112a6260d5a15e18c9
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: 2.0.0-beta7
    created: "2023-02-06T09:18:08.210090485Z"
    description: Retrieves information from Kubernetes cluster
    digest: 0ade89d01236286f11ebf70290e2c4c82740fac11ec755be9dddd2375c74246f
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-2.0.0-beta7.tgz
    version: 2.0.0-beta7
  - apiVersion: v1
    appVersion: 1.1.0
    created: "2023-02-06T09:18:08.209670181Z"
    description: Retrieves information from Kubernetes cluster
    digest: aa3ee10eefe30e61e37058762b031bdee11cb9dd67afecdf6e831335d5c16e0f
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-1.0.0.tgz
    version: 1.0.0
generated: "2023-02-06T09:18:08.209147875Z"
