apiVersion: v1
entries:
  leanix-k8s-connector:
  - apiVersion: v1
    appVersion: 2.0.0-beta1
    created: "2020-01-14T10:54:39.457614+01:00"
    description: Retrieves information from Kubernetes cluster
    digest: 9e4e6071d513c5762f52d25165fced70898934e91c10fc374c28bd8f17f89e35
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-2.0.0-beta1.tgz
    version: 2.0.0-beta1
  - apiVersion: v1
    appVersion: 1.1.0
    created: "2020-01-14T10:54:39.45708+01:00"
    description: Retrieves information from Kubernetes cluster
    digest: 1d68e40b345b9cfcf5d2793438743f3dd713b465a47de5c2a26afa1a0ddbc226
    name: leanix-k8s-connector
    urls:
    - leanix-k8s-connector-1.0.0.tgz
    version: 1.0.0
generated: "2020-01-14T10:54:39.455346+01:00"
