name: leanix-k8s-connector

on:
  push:
    branches:
      - master
      - develop
      - feature/*
    paths-ignore:
      - "helm/**"
      - "**README.md"
      - "**CHANGELOG.md"
      - "**publishNewHelmChartVersion.sh"
      - "integration-api-default-config.json"

jobs:
  register-ihub-connector-template:
    if: github.ref=='refs/heads/master' || github.ref=='refs/heads/develop'
    name: deploy and register to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: [ westeurope, eastus, canadacentral, australiaeast, germanywestcentral ]

    steps:
      - name: Checkout
          uses: actions/checkout@v2

      - name: Get credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - name: Register k8s Connector on ${{ matrix.cluster }} cluster
        uses: leanix/integration-hub-connector-register-action@main
        with:
          region: ${{ matrix.cluster }}
          environment: 'prod'
          connector_definition_file: 'ihub-resources/connector-definition.json'
          connector_icon: 'ihub-resources/connector-k8s-icon.png'

  main:
    name: leanix-k8s-connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          VERSION=$(make version)
          make
          make image
          docker run leanixacrpublic.azurecr.io/leanix-k8s-connector:${VERSION} --help | grep "pflag: help requested"

      - name: Docker login and push image to Docker Hub
        if: github.ref=='refs/heads/master' || github.ref=='refs/heads/develop'
        run: |
          echo ${{ secrets.ACR_PUBLIC_PASSWORD }} | docker login -u ${{ secrets.ACR_PUBLIC_USERNAME }} --password-stdin ${{ secrets.ACR_PUBLIC_LOGIN }}
          make push
