name: leanix-k8s-connector

on:
  push:
    branches:
      - master
      - develop
      - feature/**
      - bugfix/**
    paths-ignore:
      - "helm/**"
      - "**README.md"
      - "**CHANGELOG.md"
      - "**publishNewHelmChartVersion.sh"
      - "integration-api-default-config.json"
      - 'ihub-resources/**'

jobs:
  main:
    name: leanix-k8s-connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go version
        uses: actions/setup-go@v2
          with:
            go-version: '1.16.10'

      - name: Build and test
        run: |
          VERSION=$(make version)
          make
          make image
          docker run leanixacrpublic.azurecr.io/leanix-k8s-connector:${VERSION} --help | grep "pflag: help requested"

      - name: Docker login and push image to Docker Hub
        if: github.ref=='refs/heads/master'
        run: |
          echo ${{ secrets.ACR_PUBLIC_PASSWORD }} | docker login -u ${{ secrets.ACR_PUBLIC_USERNAME }} --password-stdin ${{ secrets.ACR_PUBLIC_LOGIN }}
          make push
