name: leanix-k8s-connector

on:
  push:
    branches:
      - master
      - develop
      - feature/**
      - bugfix/**
    paths-ignore:
      - "helm/**"
      - "**README.md"
      - "**CHANGELOG.md"
      - "**publishNewHelmChartVersion.sh"
      - "integration-api-default-config.json"
      - 'ihub-resources/**'

jobs:
  main:
    name: leanix-k8s-connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.3

      - name: Build and test
        run: |
          VERSION=$(make version)
          go install github.com/golang/mock/mockgen
          make build gen
          make test