name: leanix-k8s-connector

on:
  push:
    branches:
    - master
    - develop
    - feature/*
    paths-ignore:
    - 'helm/**'
    - '**README.md'

jobs:
  main:
    name: leanix-k8s-connector
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        VERSION=$(make version)
        make
        make image
        docker run leanix/leanix-k8s-connector:${VERSION} --help | grep "pflag: help requested"

    - name: Docker login and push image to Docker Hub
      if: github.ref=='refs/heads/master' && github.ref=='refs/heads/develop'
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        make push