name: Snyk vulnerability scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-go@master
        with:
          go-version: 1.18.3

      - name: Setup project
        run: make clean gen

      - name: Show current used versions
        run: go list -m all

      - uses: snyk/actions/golang@master
        with:
          command: monitor -d --project-tags=Team=Helios,Tribe=VSM --project-name=leanix/leanix-k8s-connector